// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.........f......
.......ff7f.....
.....ff777f.....
.....f777ffff...
....f77fffeef...
.....ffeeeeef...
.....fffeefff...
.....feeeeeef...
.....ffffffff...
........ff......
......ff77ff....
.....ff7777ff...
....f7f7777f7f..
....f7f7777f7f..
....f7f7777f7f..
....fff7777fff..
......f7777f....
......ffffff....
......f7ff7f....
......ffffff....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
